{% set name = "turborepo" %}
{% set version = "2.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/vercel/turborepo/archive/v{{ version }}.tar.gz
  sha256: 4445a3a1877812fe9fe4ec8a103050f0839dbcc0a22c3fe4d14d9bebafa71dbc

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - capnproto
    - cargo-bundle-licenses
    - libprotobuf
    - lld  # [linux]

test:
  commands:
    - turbo --help

about:
  home: https://github.com/vercel/turborepo/
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Build system optimized for JavaScript and TypeScript, written in Rust
  dev_url: https://github.com/vercel/turborepo/

extra:
  recipe-maintainers:
    - danielnachun
