context:
  version: "2.9.11"

package:
  name: turborepo
  version: ${{ version }}

source:
  url: https://github.com/vercel/turborepo/archive/v${{ version }}.tar.gz
  sha256: 7720e6d96bdabe51fb7cae82dbc31925b0177036a5e105ab24083d6b7e0e5b30

build:
  number: 0
  skip: win or ppc64le

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - capnproto
    - cargo-bundle-licenses
    - libprotobuf
    - if: linux
      then: lld

tests:
  - script:
      - turbo --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Build system optimized for JavaScript and TypeScript, written in Rust
  homepage: https://github.com/vercel/turborepo/
  repository: https://github.com/vercel/turborepo/

extra:
  recipe-maintainers:
    - danielnachun
