context:
  version: "2.9.0"

package:
  name: turborepo
  version: ${{ version }}

source:
  url: https://github.com/vercel/turborepo/archive/v${{ version }}.tar.gz
  sha256: 0f8fccdcc600de586f3c5fbe6db8337cb2d18a4364c7f9e9b9fbff2ca4c0cd50

build:
  number: 0
  skip: win or ppc64le

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - capnproto
    - cargo-bundle-licenses
    - libprotobuf
    - if: linux
      then: lld

tests:
  - script:
      - turbo --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Build system optimized for JavaScript and TypeScript, written in Rust
  homepage: https://github.com/vercel/turborepo/
  repository: https://github.com/vercel/turborepo/

extra:
  recipe-maintainers:
    - danielnachun
