context:
  version: "2.9.14"

package:
  name: turborepo
  version: ${{ version }}

source:
  url: https://github.com/vercel/turborepo/archive/v${{ version }}.tar.gz
  sha256: afe2f1a67d91290bec61cce885220e9f18c14b38e5e1fae8c519ad4e7ccd2925

build:
  number: 0
  skip: win or ppc64le

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - capnproto
    - cargo-bundle-licenses
    - libprotobuf
    - if: linux
      then: lld

tests:
  - script:
      - turbo --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Build system optimized for JavaScript and TypeScript, written in Rust
  homepage: https://github.com/vercel/turborepo/
  repository: https://github.com/vercel/turborepo/

extra:
  recipe-maintainers:
    - danielnachun
