context:
  version: "2.4.3"

package:
  name: turborepo
  version: ${{ version }}

source:
  url: https://github.com/vercel/turborepo/archive/v${{ version }}.tar.gz
  sha256: d3f87d43c227df47e69a84a25c89cae1b18f09313484ba695f0a46003a073c78

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - capnproto
    - cargo-bundle-licenses
    - libprotobuf
    - if: linux
      then: lld

tests:
  - script:
      - turbo --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Build system optimized for JavaScript and TypeScript, written in Rust
  homepage: https://github.com/vercel/turborepo/
  repository: https://github.com/vercel/turborepo/

extra:
  recipe-maintainers:
    - danielnachun
