context:
  version: "2.6.2"

package:
  name: turborepo
  version: ${{ version }}

source:
  url: https://github.com/vercel/turborepo/archive/v${{ version }}.tar.gz
  sha256: d1805b897d6786f66204257d0f1556fbf7f33b50c3587bc7e82d7bcc33f5b491

build:
  number: 0
  skip: win or ppc64le

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - capnproto
    - cargo-bundle-licenses
    - libprotobuf
    - if: linux
      then: lld

tests:
  - script:
      - turbo --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Build system optimized for JavaScript and TypeScript, written in Rust
  homepage: https://github.com/vercel/turborepo/
  repository: https://github.com/vercel/turborepo/

extra:
  recipe-maintainers:
    - danielnachun
